config/routes.rb
CorpaSystem::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :blog do
      resources :price_lists
    end
    resources :factory do
      resources :price_lists
    end
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "home" }

  resources :blog do
    member do
      post :comments
      get :comments
      get :constructions
    end
  end

  get 'blog/:id/constructions' => 'blog#constructions', as: :blog_calculator
  get 'blog/:id/constructions/:construction_id' => 'blog#construction'

  root to: "home#index"
  get 'user_agreement' => 'home#user_agreement', as: :user_agreement

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  acts_as_commentable
  has_one :photo, as: :imageable, dependent: :destroy
  has_many :price_lists, as: :priceable, dependent: :destroy


  scope :filter, -> (id){ where(city_id: id) }

  belongs_to :admin_user
  belongs_to :city
  belongs_to :factory

  attr_accessible :name, :description, :photo_attributes, :admin_user_id, :lat, :long, :factory_id, :city_id, :created_at

  validates :name, :description, :lat, :long, :admin_user_id, :factory_id, :city_id, :photo, presence: true
  validates :lat , numericality: {  greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :long, numericality: {  greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }

  accepts_nested_attributes_for :photo


  def price_lists_json
    factory_prices = factory.price_lists.all.inject({}){ |memo, model| memo[model.name] = JSON.parse(model.area_sizes_prices_json); memo; }
    company_prices = price_lists.all.inject({}){ |memo, model| memo[model.name] = JSON.parse(model.area_sizes_prices_json); memo; }
    factory_prices.merge(company_prices).to_json
  end




end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :authenticate_user!, only: [:comments]
  before_action :find_blog, only: [:show, :comments, :constructions, :construction]

  def index
    @blogs = if params[:q]
      Blog.filter(params[:q]).includes(:photo).page(params[:page]).per(9)
    else
      Blog.all.includes(:photo).page(params[:page]).per(9)
    end
  end

  def show

  end

  def comments
  	if request.post?
      @blog.comments.create(comment_params)
    end
    redirect_to blog_path(@blog)
  end

  def constructions
    @constructions = Construction.all.to_a
  end

  def construction
    @construction = Construction.find params[:construction_id]
    render layout: false
  end


  private

   def comment_params
      params[:comment][:user_id] = current_user.id
      params.require(:comment).permit(:comment, :user_id)
    end

  def find_blog
    @blog = Blog.find params[:id]
    @comments = @blog.comments.includes(:user).page(params[:page]).per(10)
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_comment.slim
.comment
  .row
    .col-sm-2
      = image_tag(comment.user.avatar_or_no_user_url, { class: "img-circle author_pic", size: "50x50" })
    div.col-sm-10
      .name
        #{comment.user.name}
        a.reply href="#"
      .date
        #{l comment.created_at, format: :long}
      .response
        = comment.comment

app/views/blog/_comment_form.slim
.new_comment
  h4= t('comment.add')
  = form_tag(comments_blog_path([@blog.id])) do |f|
    .row
      .col-sm-12
        textarea.form-control placeholder=t('comment.comments') rows="7" name='comment[comment]'
    .row
      .col-sm-12
        = submit_tag t('comment.add'), class: "btn send"

app/views/blog/_google_map.slim
coffee:
  [lat, long] = $('.office-lat-long').data('cord').split(',')
  map = ""
  TILE_SIZE = 256;
  chicago = new google.maps.LatLng(lat, long);
  bound = (value, opt_min, opt_max) ->
    value = Math.max(value, opt_min) if (opt_min != null)
    value = Math.min(value, opt_max) if (opt_max != null)
    value
  degreesToRadians = (deg) ->
    deg * (Math.PI / 180)
  radiansToDegrees = (rad) ->
    rad / (Math.PI / 180);
  MercatorProjection = () ->
    this.pixelOrigin_ = new google.maps.Point(TILE_SIZE / 2, TILE_SIZE / 2)
    this.pixelsPerLonDegree_ = TILE_SIZE / 360
    this.pixelsPerLonRadian_ = TILE_SIZE / (2 * Math.PI)
  MercatorProjection.prototype.fromLatLngToPoint = (latLng, opt_point) ->
    me = this
    point = opt_point || new google.maps.Point(0, 0)
    origin = me.pixelOrigin_
    point.x = origin.x + latLng.lng() * me.pixelsPerLonDegree_;
    siny = bound(Math.sin(degreesToRadians(latLng.lat())), -0.9999, 0.9999)
    point.y = origin.y + 0.5 * Math.log((1 + siny) / (1 - siny)) * -me.pixelsPerLonRadian_
    point
  MercatorProjection.prototype.fromPointToLatLng = (point) ->
    me = this
    origin = me.pixelOrigin_
    lng = (point.x - origin.x) / me.pixelsPerLonDegree_
    latRadians = (point.y - origin.y) / -me.pixelsPerLonRadian_
    lat = radiansToDegrees(2 * Math.atan(Math.exp(latRadians)) -Math.PI / 2)
    new google.maps.LatLng(lat, lng)
  createInfoWindowContent = () ->
    numTiles = 1 << map.getZoom()
    projection = new MercatorProjection()
    worldCoordinate = projection.fromLatLngToPoint(chicago)
    pixelCoordinate = new google.maps.Point(worldCoordinate.x * numTiles, worldCoordinate.y * numTiles)
    tileCoordinate = new google.maps.Point( Math.floor(pixelCoordinate.x / TILE_SIZE), Math.floor(pixelCoordinate.y / TILE_SIZE))
    [
      $('.office-lat-long').data('desc')
      ""
    ].join('<br>');
  initialize = ()->
    mapOptions =
      zoom: 14,
      center: chicago
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    coordInfoWindow = new google.maps.InfoWindow();
    coordInfoWindow.setContent(createInfoWindowContent());
    coordInfoWindow.setPosition(chicago);
    coordInfoWindow.open(map);
    google.maps.event.addListener(map, 'zoom_changed', () ->
      coordInfoWindow.setContent(createInfoWindowContent());
      coordInfoWindow.open(map);
    )
  google.maps.event.addDomListener(window, 'load', initialize)
  google.maps.event.addDomListener(document, 'page:load', initialize)

app/views/blog/_post.slim
.col-sm-4
  .post
    .img
      a href=blog_path(post)
        = image_tag(post.photo.photo, alt: post.photo.description, size: "360x300" ) if post.photo
    .text
      h5 = post.name
        a href='#'
      span.date=l post.created_at.to_date, format: :long
      p=post.description
    .author_box
      h6= "ЧП #{post.admin_user.try(:name)}"
    .author_box
      h6=link_to("Оконный Калькулятор", blog_calculator_path(post))

app/views/blog/_recent_posts.slim
.sidebar_header
  h4=t "comment.recent"
- @comments.last(5).each do |c|
  .recent.comment
    span
      = image_tag(c.user.avatar_or_no_user_url	, size: "56x59")
    .name
      #{c.user.name}
      a.reply href="#"
    .date
      #{l c.created_at, format: :long}
    p= c.comment

app/views/blog/_search_form.slim
= form_tag blog_index_path, method: :get do
  = select_tag :q, options_for_select(City.all.collect{ |u| [u.name, u.id] }, selected: params[:q]), include_blank: true, onchange: "this.form.submit();", class: "form-control"

app/views/blog/_sidebar.slim
.col-sm-4
  .sidebar
    .box.box2
      = render 'blog/recent_posts'

app/views/blog/construction.slim
#calc.container data-groups=@construction.groups.keys
  = render "window_calc/construction" , construction: @construction

app/views/blog/constructions.slim
- content_for(:title)
  = "ЧП #{@blog.admin_user.try(:name)}"
#content
  #price_list data-price=@blog.price_lists_json
  #all_leafs.hide
    - Construction::LEAFS.each do |l|
      = image_tag image_to_base64("alt/#{l}.png"), { "class" => "img-responsive window_img", "data-type" => "window", "data-kind" => l }
    - Construction::DOORS.each do |l|
      = image_tag image_to_base64("alt/#{l}.png"), { "class" => "img-responsive door_img", "data-type" => 'door', "data-kind" => l }
- if @constructions.size > 0
  br
  #calc_left.col-md-9
    span: p.bg-primary  Нажми левым щелчком мыши на конструкцию для изменения конфигурации.
    br
    br
    #window_with_sliders
      #calc.container data-groups=@constructions.first.groups.keys
        = render "window_calc/construction" , construction: @constructions.first
    .row
      .col-md-2
      .col-md-5
        br
        label Примерная стоимость изделия: &nbsp;
        span#construction-cost.text-left 0
        span &nbsp; грн.
      .col-md-2
      .col-md-3
        br
        button#cost_btn.btn.btn-info Рассчитать стоимость


  #calc_right.col-md-3
    br
    br
    #calc_type
      .title Тип окна
      ul
        - @constructions.each do |i|
          li id=i.id
            = image_tag i.photo.photo, "data-id" => i.id
    = render "window_calc/form"
- else
  span Информация о стоимости обновляется...
  div style="height:420px"

app/views/blog/index.slim
#blog
  .container
    .section_header
      h3=t 'office.find'
      br
      br
      = render partial: 'blog/search_form'
    .row.post_row
      = render partial: 'blog/post', collection: @blogs
    = paginate @blogs if @blogs.num_pages > 1

app/views/blog/show.slim
#blog_post
  .container
    .section_header
      h3=t('office.page')
    .row
      .col-sm-8.office-lat-long data-cord="#{@blog.long}, #{@blog.lat}" data-desc=t('office.location')
        = render 'blog/google_map'
        #map-canvas.post_pic.img-responsive
        .post_content
          h2= @blog.name
          span.date #{l @blog.created_at.to_date, format: :long}
          p
            #{@blog.description}
          .author_box
            .author
              = "ЧП #{@blog.admin_user.try(:name)}"
        - if  @comments.size > 0
          .comments
            h4= t 'comment.comments'
            = render partial: 'blog/comment', collection: @comments
            = paginate(@comments) if  @comments.num_pages > 1
          br
        = render 'blog/comment_form'
      = render 'blog/sidebar' if @comments.size > 0
- content_for(:title)
  = "ЧП #{@blog.admin_user.try(:name)}"