config/routes.rb
CorpaSystem::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :blog do
      resources :price_lists
    end
    resources :factory do
      resources :price_lists
    end
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "home" }

  resources :blog do
    member do
      post :comments
      get :comments
      get :constructions
    end
  end

  get 'blog/:id/constructions' => 'blog#constructions', as: :blog_calculator
  get 'blog/:id/constructions/:construction_id' => 'blog#construction'

  root to: "home#index"
  get 'user_agreement' => 'home#user_agreement', as: :user_agreement

end

app/views/layouts/_footer.slim
footer#footer
  .container
    .row.text-center
      .col-md-12
        strong
          | Developed by &nbsp;
          a href="http://about.me/kutskosergey" Sergey Kutsko
    .row.text-center
      .col-md-12
        | © 2013 Clean Canvas. All rights reserved. Theme by Detail Canvas.

app/views/layouts/_header.slim
.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.pull-right data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href=root_path
        strong
           = content_for?(:title) ? yield(:title) : t('header.corpa_system')
    .collapse.navbar-collapse.navbar-ex1-collapse role="navigation"
      ul.nav.navbar-nav.navbar-right.nav-tabs
        li: a  href=root_path =t('header.home')
        li: a  href="#" =t('header.about')
        li= link_to t('header.blog'), blog_index_path
        - unless current_user
          li = link_to t('header.sign_up'), new_user_registration_path
          li = link_to t('header.sign_in'), new_user_session_path
        - else
          li: a= current_user.name
          li= link_to t('header.sign_out'), destroy_user_session_path(params: { authenticity_token: form_authenticity_token }), method: :delete
        li= link_to t('header.user_agreement'), user_agreement_path

app/views/layouts/application.slim
html
  head
    meta charset="utf-8"
    meta name="viewport" content="initial-scale=1.0, user-scalable=no"

    title Corpо System

    script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"

    link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"

    = stylesheet_link_tag 'application'
    = javascript_include_tag "application"

  body
    = flash[:info]
    = render 'layouts/header'
    .container-fluid style="padding-left: 0px; padding-right: 0px;"
     = yield
    br
    br
    br
    br
    br
    = render 'layouts/footer'